"""Initial

Revision ID: c0e5b723199d
Revises: 
Create Date: 2023-07-17 18:30:55.070241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e5b723199d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parsed_patents_count', sa.Integer(), nullable=False),
    sa.Column('missed_patents_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('patent_title', sa.Text(), nullable=False),
    sa.Column('document_number', sa.String(length=255), nullable=True),
    sa.Column('patent_owner', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('applicant', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('international_patent_classification', sa.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_table('website_parsing_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('publication_date_selector_value', sa.String(length=255), nullable=False),
    sa.Column('patent_title_selector_value', sa.String(length=255), nullable=False),
    sa.Column('document_number_selector_value', sa.String(length=255), nullable=False),
    sa.Column('patent_owner_selector_value', sa.String(length=255), nullable=False),
    sa.Column('applicant_selector_value', sa.String(length=255), nullable=False),
    sa.Column('international_patent_classification_selector_value', sa.String(length=255), nullable=False),
    sa.Column('country_selector_value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_parsing_config')
    op.drop_table('patents')
    op.drop_table('logs')
    # ### end Alembic commands ###
