"""Initial revision

Revision ID: fd9710ba9910
Revises: 
Create Date: 2023-07-12 19:45:53.391328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9710ba9910'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.String(length=255), nullable=False),
                    sa.Column('last_name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('parsing_information',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('url', sa.Text(), nullable=False),
                    sa.Column('selector_type', sa.String(length=255), nullable=False),
                    sa.Column('element_selector_value', sa.String(length=255), nullable=False),
                    sa.Column('selectors_value', sa.ARRAY(sa.String(length=255)), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('patents',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('publication_date', sa.Date(), nullable=False),
                    sa.Column('patent_title', sa.String(length=255), nullable=False),
                    sa.Column('document_number', sa.String(length=255), nullable=True),
                    sa.Column('patent_owner', sa.ARRAY(sa.String(length=255)), nullable=True),
                    sa.Column('applicant', sa.ARRAY(sa.String(length=255)), nullable=True),
                    sa.Column('international_patent_classification', sa.ARRAY(sa.String(length=255)), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('logs',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('level', sa.String(length=255), nullable=True),
                    sa.Column('status', sa.String(length=255), nullable=False),
                    sa.Column('message', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
                    sa.Column('parsing_info_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parsing_info_id'], ['parsing_information.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('patents_authors',
                    sa.Column('patent_id', sa.Integer(), nullable=False),
                    sa.Column('author_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
                    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
                    sa.PrimaryKeyConstraint('patent_id', 'author_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patents_authors')
    op.drop_table('logs')
    op.drop_table('patents')
    op.drop_table('parsing_information')
    op.drop_table('authors')
    # ### end Alembic commands ###
